// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Mandor_UI

#ifndef UI_SCREEN9_H
#define UI_SCREEN9_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen9
extern void ui_Screen9_screen_init(void);
extern void ui_Screen9_screen_destroy(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label32;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Arc4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

