// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Mandor_UI

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Button18 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel6, 480);
    lv_obj_set_height(ui_Panel6, 282);
    lv_obj_set_x(ui_Panel6, -1);
    lv_obj_set_y(ui_Panel6, 2);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x494444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -153);
    lv_obj_set_y(ui_Label16, -88);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Tentang Projek ini :");

    ui_Label17 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "");

    ui_TextArea1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea1, 438);
    lv_obj_set_height(ui_TextArea1, 157);
    lv_obj_set_x(ui_TextArea1, -3);
    lv_obj_set_y(ui_TextArea1, 7);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1,
                         "Proyek ini mengembangkan sistem **predictive maintenance berbasis IoT dan Edge AI** untuk meningkatkan efisiensi serta mengurangi *unplanned downtime* pada sistem konveyor industri. Sistem menggunakan ESP32 dan berbagai sensor untuk memantau kondisi motor secara *real-time*, seperti getaran, suhu, arus, dan kecepatan, kemudian mengirimkan data melalui MQTT untuk dianalisis oleh Edge AI. Ketika terdeteksi anomali, sistem secara otomatis menyesuaikan PWM motor agar kecepatannya menurun sehingga dapat mencegah *overheat*, mengurangi konsumsi energi, dan menjaga operasional tetap berjalan. Selain itu, sistem menerapkan konsep **Fleet Management** melalui Web Dashboard dan **Digital Twin berbasis Unity 3D** untuk memberikan pemantauan kondisi mesin secara terpusat, interaktif, dan komprehensif.\n");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Button11 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button11, 100);
    lv_obj_set_height(ui_Button11, 32);
    lv_obj_set_x(ui_Button11, -166);
    lv_obj_set_y(ui_Button11, 113);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -167);
    lv_obj_set_y(ui_Label23, 112);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Back");

    ui_Label31 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -8);
    lv_obj_set_y(ui_Label31, -115);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "MANDOR - PREDICTIVE MAINTENANCE");

    ui_Button18 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button18, 100);
    lv_obj_set_height(ui_Button18, 32);
    lv_obj_set_x(ui_Button18, 175);
    lv_obj_set_y(ui_Button18, 113);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 177);
    lv_obj_set_y(ui_Label8, 113);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Member");

    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel6 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_TextArea1 = NULL;
    ui_Button11 = NULL;
    ui_Label23 = NULL;
    ui_Label31 = NULL;
    ui_Button18 = NULL;
    ui_Label8 = NULL;

}
