// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Mandor_UI

#ifndef UI_SCREEN7_H
#define UI_SCREEN7_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen7
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Chart4;
extern lv_obj_t * ui_Chart4_Xaxis;
extern lv_obj_t * ui_Chart4_Yaxis1;
extern lv_obj_t * ui_Chart4_Yaxis2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

