// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Mandor_UI

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label54;
extern void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Chart5;
extern lv_obj_t * ui_Chart5_Xaxis;
extern lv_obj_t * ui_Chart5_Yaxis1;
extern lv_obj_t * ui_Chart5_Yaxis2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

