// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Mandor_UI

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Label40 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen9, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen9_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel5, 480);
    lv_obj_set_height(ui_Panel5, 282);
    lv_obj_set_x(ui_Panel5, -1);
    lv_obj_set_y(ui_Panel5, 2);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x494444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -4);
    lv_obj_set_y(ui_Label30, -95);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "MANDOR - PREDICTIVE MAINTENANCE");

    ui_Button3 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button3, 191);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -120);
    lv_obj_set_y(ui_Button3, -25);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button5, 191);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 109);
    lv_obj_set_y(ui_Button5, -25);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button8, 191);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, -120);
    lv_obj_set_y(ui_Button8, 39);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button15 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button15, 191);
    lv_obj_set_height(ui_Button15, 50);
    lv_obj_set_x(ui_Button15, 109);
    lv_obj_set_y(ui_Button15, 39);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -119);
    lv_obj_set_y(ui_Label13, -23);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Temperature");

    ui_Label14 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 111);
    lv_obj_set_y(ui_Label14, -23);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Vibration");

    ui_Label15 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -121);
    lv_obj_set_y(ui_Label15, 39);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Current");

    ui_Label35 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 106);
    lv_obj_set_y(ui_Label35, 39);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Rotation Speed");

    ui_Button16 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button16, 191);
    lv_obj_set_height(ui_Button16, 50);
    lv_obj_set_x(ui_Button16, -7);
    lv_obj_set_y(ui_Button16, 103);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -8);
    lv_obj_set_y(ui_Label40, 104);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Overall Status");

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Panel5 = NULL;
    ui_Label30 = NULL;
    ui_Button3 = NULL;
    ui_Button5 = NULL;
    ui_Button8 = NULL;
    ui_Button15 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label35 = NULL;
    ui_Button16 = NULL;
    ui_Label40 = NULL;

}
