// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Mandor_UI

#include "ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_Arc3 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Button19 = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_Label48 = NULL;
lv_obj_t * ui_Button20 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_Chart4 = NULL;
lv_obj_t * ui_Chart4_Xaxis = NULL;
lv_obj_t * ui_Chart4_Yaxis1 = NULL;
lv_obj_t * ui_Chart4_Yaxis2 = NULL;
// event funtions
void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel13, 480);
    lv_obj_set_height(ui_Panel13, 282);
    lv_obj_set_x(ui_Panel13, 0);
    lv_obj_set_y(ui_Panel13, 3);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x494444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -8);
    lv_obj_set_y(ui_Label44, -115);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "MANDOR - PREDICTIVE MAINTENANCE");

    ui_Arc3 = lv_arc_create(ui_Screen7);
    lv_obj_set_width(ui_Arc3, 150);
    lv_obj_set_height(ui_Arc3, 150);
    lv_obj_set_x(ui_Arc3, -127);
    lv_obj_set_y(ui_Arc3, 8);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc3, 0, 500);
    lv_arc_set_value(ui_Arc3, 50);

    ui_Label45 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -126);
    lv_obj_set_y(ui_Label45, 5);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "0.01A");

    ui_Button19 = lv_button_create(ui_Screen7);
    lv_obj_set_width(ui_Button19, 100);
    lv_obj_set_height(ui_Button19, 50);
    lv_obj_set_x(ui_Button19, 175);
    lv_obj_set_y(ui_Button19, 105);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0xEB3131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 179);
    lv_obj_set_y(ui_Label46, 106);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "Reset");

    ui_Panel14 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel14, 44);
    lv_obj_set_height(ui_Panel14, 40);
    lv_obj_set_x(ui_Panel14, 82);
    lv_obj_set_y(ui_Panel14, 112);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x19F505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 82);
    lv_obj_set_y(ui_Label47, 81);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "Status");

    ui_Label48 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, -4);
    lv_obj_set_y(ui_Label48, -89);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "Current");

    ui_Button20 = lv_button_create(ui_Screen7);
    lv_obj_set_width(ui_Button20, 100);
    lv_obj_set_height(ui_Button20, 32);
    lv_obj_set_x(ui_Button20, -166);
    lv_obj_set_y(ui_Button20, 113);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label49 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -167);
    lv_obj_set_y(ui_Label49, 112);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "Kembali");

    ui_Chart4 = lv_chart_create(ui_Screen7);
    lv_obj_set_width(ui_Chart4, 200);
    lv_obj_set_height(ui_Chart4, 100);
    lv_obj_set_x(ui_Chart4, 102);
    lv_obj_set_y(ui_Chart4, -8);
    lv_obj_set_align(ui_Chart4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart4, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart4, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart4, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart4, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_range(ui_Chart4, LV_CHART_AXIS_PRIMARY_Y, 0, 500);

    ui_Chart4_Xaxis = lv_scale_create(ui_Chart4);
    lv_scale_set_mode(ui_Chart4_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart4_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart4_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart4_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart4,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart4, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart4_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart4_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart4_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart4_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart4_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart4_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart4_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart4_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart4_Yaxis1 = lv_scale_create(ui_Chart4);
    lv_scale_set_mode(ui_Chart4_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart4_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart4_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart4_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart4,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart4, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart4_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart4_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart4_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart4_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart4_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart4_Yaxis1,  0, 500);
    lv_scale_set_total_tick_count(ui_Chart4_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart4_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart4_Yaxis2 = lv_scale_create(ui_Chart4);
    lv_scale_set_mode(ui_Chart4_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart4_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart4_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart4_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart4,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart4, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart4_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart4_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart4_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart4_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart4_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart4_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart4_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart4_series_1 = lv_chart_add_series(ui_Chart4, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart4_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_series_ext_y_array(ui_Chart4, ui_Chart4_series_1, ui_Chart4_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart4, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart4, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Panel13 = NULL;
    ui_Label44 = NULL;
    ui_Arc3 = NULL;
    ui_Label45 = NULL;
    ui_Button19 = NULL;
    ui_Label46 = NULL;
    ui_Panel14 = NULL;
    ui_Label47 = NULL;
    ui_Label48 = NULL;
    ui_Button20 = NULL;
    ui_Label49 = NULL;
    ui_Chart4 = NULL;

}
