// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Mandor_UI

#include "ui.h"

lv_obj_t * ui_Screen9 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Arc4 = NULL;
// event funtions
void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Screen9);
    lv_obj_set_width(ui_Panel4, 480);
    lv_obj_set_height(ui_Panel4, 282);
    lv_obj_set_x(ui_Panel4, 4);
    lv_obj_set_y(ui_Panel4, -1);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x494444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -8);
    lv_obj_set_y(ui_Label22, -115);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "MANDOR - PREDICTIVE MAINTENANCE");

    ui_Button10 = lv_button_create(ui_Screen9);
    lv_obj_set_width(ui_Button10, 100);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, 182);
    lv_obj_set_y(ui_Button10, 103);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xEB3131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 184);
    lv_obj_set_y(ui_Label26, 102);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Reset");

    ui_Label32 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -2);
    lv_obj_set_y(ui_Label32, -83);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Overall Status");

    ui_Button13 = lv_button_create(ui_Screen9);
    lv_obj_set_width(ui_Button13, 100);
    lv_obj_set_height(ui_Button13, 32);
    lv_obj_set_x(ui_Button13, -166);
    lv_obj_set_y(ui_Button13, 113);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -166);
    lv_obj_set_y(ui_Label33, 112);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Kembali");

    ui_Label25 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -73);
    lv_obj_set_y(ui_Label25, 9);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Status : Normal");

    ui_Label28 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 76);
    lv_obj_set_y(ui_Label28, 9);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "10%");

    ui_Arc4 = lv_arc_create(ui_Screen9);
    lv_obj_set_width(ui_Arc4, 126);
    lv_obj_set_height(ui_Arc4, 150);
    lv_obj_set_x(ui_Arc4, 75);
    lv_obj_set_y(ui_Arc4, 27);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc4, 50);

    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0x25CF3D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0x0A8D48), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);

}

void ui_Screen9_screen_destroy(void)
{
    if(ui_Screen9) lv_obj_del(ui_Screen9);

    // NULL screen variables
    ui_Screen9 = NULL;
    ui_Panel4 = NULL;
    ui_Label22 = NULL;
    ui_Button10 = NULL;
    ui_Label26 = NULL;
    ui_Label32 = NULL;
    ui_Button13 = NULL;
    ui_Label33 = NULL;
    ui_Label25 = NULL;
    ui_Label28 = NULL;
    ui_Arc4 = NULL;

}
