// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Mandor_UI

#include "ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_Arc5 = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_Button21 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Label54 = NULL;
lv_obj_t * ui_Button22 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_Chart5 = NULL;
lv_obj_t * ui_Chart5_Xaxis = NULL;
lv_obj_t * ui_Chart5_Yaxis1 = NULL;
lv_obj_t * ui_Chart5_Yaxis2 = NULL;
// event funtions
void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel15 = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_Panel15, 480);
    lv_obj_set_height(ui_Panel15, 282);
    lv_obj_set_x(ui_Panel15, 0);
    lv_obj_set_y(ui_Panel15, 3);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x494444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -8);
    lv_obj_set_y(ui_Label50, -115);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "MANDOR - PREDICTIVE MAINTENANCE");

    ui_Arc5 = lv_arc_create(ui_Screen8);
    lv_obj_set_width(ui_Arc5, 150);
    lv_obj_set_height(ui_Arc5, 150);
    lv_obj_set_x(ui_Arc5, -127);
    lv_obj_set_y(ui_Arc5, 8);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc5, 50);

    ui_Label51 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -126);
    lv_obj_set_y(ui_Label51, 5);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "28RPM");

    ui_Button21 = lv_button_create(ui_Screen8);
    lv_obj_set_width(ui_Button21, 100);
    lv_obj_set_height(ui_Button21, 50);
    lv_obj_set_x(ui_Button21, 175);
    lv_obj_set_y(ui_Button21, 105);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button21, lv_color_hex(0xEB3131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, 179);
    lv_obj_set_y(ui_Label52, 106);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "Reset");

    ui_Panel16 = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_Panel16, 44);
    lv_obj_set_height(ui_Panel16, 40);
    lv_obj_set_x(ui_Panel16, 82);
    lv_obj_set_y(ui_Panel16, 112);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x19F505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, 82);
    lv_obj_set_y(ui_Label53, 81);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "Status");

    ui_Label54 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -4);
    lv_obj_set_y(ui_Label54, -89);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "Rotation Speed");

    ui_Button22 = lv_button_create(ui_Screen8);
    lv_obj_set_width(ui_Button22, 100);
    lv_obj_set_height(ui_Button22, 32);
    lv_obj_set_x(ui_Button22, -166);
    lv_obj_set_y(ui_Button22, 113);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label55 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, -167);
    lv_obj_set_y(ui_Label55, 112);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "Kembali");

    ui_Chart5 = lv_chart_create(ui_Screen8);
    lv_obj_set_width(ui_Chart5, 200);
    lv_obj_set_height(ui_Chart5, 100);
    lv_obj_set_x(ui_Chart5, 102);
    lv_obj_set_y(ui_Chart5, -8);
    lv_obj_set_align(ui_Chart5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart5, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart5, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart5, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart5, LV_CHART_TYPE_LINE);

    ui_Chart5_Xaxis = lv_scale_create(ui_Chart5);
    lv_scale_set_mode(ui_Chart5_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart5_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart5_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart5_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart5,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart5, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart5_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart5_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart5_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart5_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart5_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart5_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart5_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart5_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart5_Yaxis1 = lv_scale_create(ui_Chart5);
    lv_scale_set_mode(ui_Chart5_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart5_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart5_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart5_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart5,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart5, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart5_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart5_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart5_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart5_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart5_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart5_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart5_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart5_Yaxis2 = lv_scale_create(ui_Chart5);
    lv_scale_set_mode(ui_Chart5_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart5_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart5_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart5_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart5,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart5, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart5_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart5_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart5_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart5_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart5_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart5_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart5_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart5_series_1 = lv_chart_add_series(ui_Chart5, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart5_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_series_ext_y_array(ui_Chart5, ui_Chart5_series_1, ui_Chart5_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart5, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart5, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_Panel15 = NULL;
    ui_Label50 = NULL;
    ui_Arc5 = NULL;
    ui_Label51 = NULL;
    ui_Button21 = NULL;
    ui_Label52 = NULL;
    ui_Panel16 = NULL;
    ui_Label53 = NULL;
    ui_Label54 = NULL;
    ui_Button22 = NULL;
    ui_Label55 = NULL;
    ui_Chart5 = NULL;

}
